/**
 * Official board layouts, and the generated layouts for player counts the game does not cover.
 *
 * Component counts here are transcribed from the rulebooks and are the authority for the rest of
 * the engine — see `presets.test.ts`, which checks every one of them against the printed tables.
 *
 * | | 3-4 players | 5-6 players |
 * |---|---|---|
 * | Land hexes | 19 — 4 forest, 4 pasture, 4 fields, 3 hills, 3 mountains, 1 desert | 30 — 6/6/6/5/5/2 |
 * | Number tokens | 18 — one 2, one 12, two each of 3,4,5,6,8,9,10,11 | 28 — two 2, two 12, three each of the rest |
 * | Harbours | 9 — 4 generic 3:1, 5 specific 2:1 (one per resource) | 11 — 5 generic, 6 specific (wool twice) |
 * | Bank per resource | 19 | 24 |
 *
 * **There are no official rules above 6 players.** Boards for 7-10 are generated by scaling those
 * proportions, and are marked `unofficial` so the UI can say so.
 */

import { type HexCoord, spiral } from '../coords/axial.js';
import { BASE_RESOURCES, type CardKind, type TerrainId } from '../ids.js';
import {
  type Cell,
  type CellPlacement,
  type HarborSpec,
  type Scenario,
  type SetupRound,
  withSeaRing,
} from './scenario.js';

// ── Island shapes ───────────────────────────────────────────────────────────────────────────

/** The 3-4 player island: 19 hexes in rows of 3/4/5/4/3, exactly `spiral(2)`. */
export function island34(): readonly HexCoord[] {
  return spiral(2);
}

/**
 * The 5-6 player island: 30 hexes in rows of 3/4/5/6/5/4/3.
 *
 * Confirmed from the extension's token-placement diagram, which carries 28 letters (A-Y plus ZA,
 * ZB, ZC) over 30 hexes with 2 deserts. The bounds below place every row's centre at the same x,
 * which is the geometric confirmation that the shape is right.
 */
export function island56(): readonly HexCoord[] {
  const out: HexCoord[] = [];
  for (let r = -3; r <= 3; r++) {
    for (let q = Math.max(-3, -3 - r); q <= Math.min(2, 2 - r); q++) {
      out.push({ q, r });
    }
  }
  return out;
}

// ── Official bags ───────────────────────────────────────────────────────────────────────────

/** 4 forest, 4 pasture, 4 fields, 3 hills, 3 mountains, 1 desert. */
export const TERRAIN_BAG_34: readonly TerrainId[] = [
  ...repeat('forest', 4),
  ...repeat('pasture', 4),
  ...repeat('fields', 4),
  ...repeat('hills', 3),
  ...repeat('mountains', 3),
  ...repeat('desert', 1),
];

/** 6 forest, 6 pasture, 6 fields, 5 hills, 5 mountains, 2 desert. */
export const TERRAIN_BAG_56: readonly TerrainId[] = [
  ...repeat('forest', 6),
  ...repeat('pasture', 6),
  ...repeat('fields', 6),
  ...repeat('hills', 5),
  ...repeat('mountains', 5),
  ...repeat('desert', 2),
];

/** One 2, one 12, two each of 3-6 and 8-11. There is no 7. */
export const NUMBER_BAG_34: readonly number[] = [
  2,
  ...[3, 4, 5, 6, 8, 9, 10, 11].flatMap((n) => [n, n]),
  12,
];

/** Two 2s, two 12s, three each of 3-6 and 8-11. */
export const NUMBER_BAG_56: readonly number[] = [
  2,
  2,
  ...[3, 4, 5, 6, 8, 9, 10, 11].flatMap((n) => [n, n, n]),
  12,
  12,
];

const GENERIC_HARBOR: HarborSpec = { ratio: 3, kind: null };

function specificHarbor(kind: CardKind): HarborSpec {
  return { ratio: 2, kind };
}

/** 4 generic 3:1 plus one 2:1 for each of the five resources. */
export const HARBOR_BAG_34: readonly HarborSpec[] = [
  ...repeat(GENERIC_HARBOR, 4),
  ...BASE_RESOURCES.map(specificHarbor),
];

/**
 * 11 harbours: the base 9 plus the extension's two.
 *
 * The extension names them explicitly when describing frame assembly — a "3-3" 2:1 **wool** harbour
 * and a "5-5" 3:1 generic — so wool is the one resource with two specific harbours.
 */
export const HARBOR_BAG_56: readonly HarborSpec[] = [
  ...repeat(GENERIC_HARBOR, 5),
  ...BASE_RESOURCES.map(specificHarbor),
  specificHarbor('wool'),
];

/**
 * The base game's opening placement.
 *
 * Round one runs in seat order; round two runs **backwards**, so the last player places twice in a
 * row. Starting resources come from the second settlement only.
 */
export const BASE_SETUP: readonly SetupRound[] = [
  { order: 'forward', place: ['settlement', 'road'], grantProduction: false },
  { order: 'reverse', place: ['settlement', 'road'], grantProduction: true },
];

// ── Scenarios ───────────────────────────────────────────────────────────────────────────────

/**
 * A terrain bag as scenario `stacks` entries.
 *
 * The bag lives in `stacks` rather than on the cells because the official setup deals terrain
 * randomly: the cells fix *where* land is, the stack fixes *what is in the bag*, and `newGame`
 * shuffles one onto the other.
 */
function terrainStack(bag: readonly TerrainId[]): readonly Cell[] {
  return bag.map((terrain) => ({ kind: 'land', terrain }) as const);
}

function landCells(coords: readonly HexCoord[]): readonly CellPlacement[] {
  // Terrain is a placeholder here: the variable setup deals it from the bag at game start, and
  // `HexState` is what play reads. Scenario cells only fix *where* land is.
  return coords.map(({ q, r }) => ({ q, r, cell: { kind: 'land', terrain: 'desert' } as const }));
}

/**
 * Harbour slot count derived from the coast length.
 *
 * One harbour per ~3.3 coastal edges reproduces both official numbers from the geometry alone:
 * the 19-hex island has a 30-edge coast and 9 harbours, the 30-hex island 11.
 */
export function harborCountForCoast(coastLength: number): number {
  return Math.round(coastLength / 3.33);
}

export function baseScenario34(): Scenario {
  return {
    id: 'catan/base/3-4',
    name: 'Catan (3-4 players)',
    cells: withSeaRing(landCells(island34())),
    // Slots are computed from the coastline at setup, since they depend on the built topology.
    harborSlots: [],
    harborBag: HARBOR_BAG_34,
    stacks: { main: terrainStack(TERRAIN_BAG_34) },
    numberBags: { main: NUMBER_BAG_34 },
    victoryTarget: 10,
    setup: BASE_SETUP,
    minPlayers: 3,
    maxPlayers: 4,
    bankPerKind: 19,
  };
}

export function baseScenario56(): Scenario {
  return {
    id: 'catan/base/5-6',
    name: 'Catan (5-6 players)',
    cells: withSeaRing(landCells(island56())),
    harborSlots: [],
    harborBag: HARBOR_BAG_56,
    stacks: { main: terrainStack(TERRAIN_BAG_56) },
    numberBags: { main: NUMBER_BAG_56 },
    victoryTarget: 10,
    setup: BASE_SETUP,
    minPlayers: 5,
    maxPlayers: 6,
    bankPerKind: 24,
  };
}

/**
 * How many land hexes a generated board gets.
 *
 * Anchored on the official ratios — 19 hexes for 4 players is 4.75 each, 30 for 6 is 5.0 — so
 * ~5.2 per player continues the trend without a discontinuity at 7.
 */
export function landCountForPlayers(players: number): number {
  return Math.round(5.2 * players);
}

/** Deserts scale with the board: 1 per 19 hexes, matching 1 at 19 and 2 at 30. */
export function desertCountForLand(landHexes: number): number {
  return Math.max(1, Math.round(landHexes / 19));
}

/** Bank size per resource, extrapolated from 19 at 4 players and 24 at 6. */
export function bankForPlayers(players: number): number {
  if (players <= 4) return 19;
  if (players <= 6) return 24;
  return Math.round(24 + 5 * ((players - 6) / 2));
}

/**
 * A generated board for a player count the published game does not support.
 *
 * Deliberately marked `unofficial`: there are no rules above 6 players, so this is our own scaling
 * and the UI must not present it as the real thing.
 */
export function generatedScenario(players: number): Scenario {
  if (players < 7 || players > 10) {
    throw new Error(
      `generatedScenario: only 7-10 players are generated; ${players} has an official preset`,
    );
  }
  const count = landCountForPlayers(players);
  // spiral(5) holds 91 hexes, comfortably more than the 52 a 10-player board needs.
  const coords = spiral(5).slice(0, count);
  return {
    id: `catan/generated/${players}`,
    name: `Catan (${players} players, unofficial)`,
    cells: withSeaRing(landCells(coords)),
    harborSlots: [],
    harborBag: [],
    stacks: {},
    numberBags: {},
    victoryTarget: 10,
    setup: BASE_SETUP,
    minPlayers: players,
    maxPlayers: players,
    bankPerKind: bankForPlayers(players),
    unofficial: true,
  };
}

/** The right scenario for a player count: official presets for 3-6, generated above that. */
export function scenarioForPlayers(players: number): Scenario {
  if (players < 3 || players > 10) {
    throw new Error(`scenarioForPlayers: ${players} players is out of range (3-10)`);
  }
  if (players <= 4) return baseScenario34();
  if (players <= 6) return baseScenario56();
  return generatedScenario(players);
}

/**
 * Rebuild a scenario from its id.
 *
 * This is what makes a replay possible without shipping the board: a saved game stores
 * `scenarioId`, and every scenario built here is a pure function of that string. A scenario that
 * cannot be reconstructed from its id — one a player authored, say — has to travel with the
 * replay instead, which is why `replay` takes an override.
 */
export function scenarioById(id: string): Scenario | undefined {
  if (id === 'catan/base/3-4') return baseScenario34();
  if (id === 'catan/base/5-6') return baseScenario56();
  const generated = /^catan\/generated\/(\d+)$/.exec(id);
  if (generated !== null) return generatedScenario(Number(generated[1]));
  return undefined;
}

function repeat<T>(value: T, n: number): readonly T[] {
  return Array.from({ length: n }, () => value);
}
